/// Flutter icons SolarIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  SolarIcons
///      fonts:
///       - asset: fonts/SolarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class SolarIcons {
  SolarIcons._();

  static const _kFontFam = 'SolarIcons';

  static const IconData solar_history_bold_duotone = IconData(0xe800, fontFamily: _kFontFam,);
  static const IconData solar_restart_bold_duotone = IconData(0xe802, fontFamily: _kFontFam, );
  static const IconData solar_crown_star_bold_duotone = IconData(0xe803, fontFamily: _kFontFam, );
  static const IconData solar_round_alt_arrow_left_bold_duotone = IconData(0xe804, fontFamily: _kFontFam, );
  static const IconData data_not_found = IconData(0xe805, fontFamily: _kFontFam, );
  static const IconData solar_add_circle_bold_duotone = IconData(0xe806, fontFamily: _kFontFam, );
  static const IconData solar_star_fall_minimalistic_2_bold_duotone = IconData(0xe807, fontFamily: _kFontFam,);
  static const IconData solar_documents_bold_duotone = IconData(0xe808, fontFamily: _kFontFam, );
  static const IconData solar_shield_warning_bold_duotone = IconData(0xe809, fontFamily: _kFontFam, );
}

